# Generated by Django 3.1 on 2024-10-17 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.AutoField(primary_key=True, serialize=False)),
                ('run_administrador', models.CharField(max_length=15)),
                ('nombre_administrador', models.CharField(max_length=100)),
                ('email_administrador', models.CharField(max_length=100)),
                ('password_administrador', models.CharField(max_length=100)),
                ('telefono_administrador', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('run_cliente', models.CharField(max_length=12)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('email_cliente', models.CharField(max_length=100)),
                ('password_cliente', models.CharField(max_length=8)),
                ('telefono_cliente', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Manicurista',
            fields=[
                ('id_manicurista', models.AutoField(primary_key=True, serialize=False)),
                ('run_manicurista', models.CharField(max_length=12)),
                ('nombre_manicurista', models.CharField(max_length=100)),
                ('email_manicurista', models.CharField(max_length=100)),
                ('password_manicurista', models.CharField(max_length=8)),
                ('telefono_manicurista', models.IntegerField()),
                ('foto', models.CharField(max_length=100)),
                ('certificacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('valor', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_servicio',
            fields=[
                ('id_tipo_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_servicio', models.CharField(max_length=50)),
                ('duracion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField()),
                ('hora_reserva', models.TimeField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
    ]
