# Generated by Django 5.1.3 on 2024-11-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposervicio',
            name='descripcion',
            field=models.CharField(default=' ', max_length=250),
        ),
    ]
