# Generated by Django 5.1.3 on 2024-11-11 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_tiposervicio_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='manicurista',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='manicurista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.manicurista'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tiposervicio'),
        ),
    ]
