# Generated by Django 3.1 on 2024-11-06 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_manicurista_is_manicurista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manicurista',
            name='is_manicurista',
        ),
        migrations.AlterField(
            model_name='manicurista',
            name='certifications',
            field=models.FileField(blank=True, null=True, upload_to='certificaciones/'),
        ),
        migrations.AlterField(
            model_name='manicurista',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AlterField(
            model_name='manicurista',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
