# Generated by Django 5.1.3 on 2024-11-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_manicurista_state_alter_servicio_manicurista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manicurista',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
