# Generated by Django 5.1.3 on 2024-11-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_manicurista_motivo_rechazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manicurista',
            name='certifications',
            field=models.FileField(blank=True, null=True, upload_to='certifications/'),
        ),
    ]
