# Generated by Django 5.1.3 on 2024-11-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_manicurista_certifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='manicurista',
            name='certificado_actualizado',
            field=models.BooleanField(default=False),
        ),
    ]
