# Generated by Django 5.1.2 on 2024-11-18 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_manicurista_certificado_actualizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('horario', models.DateField()),
                ('manicurista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.manicurista')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.servicio')),
            ],
        ),
    ]
