# Generated by Django 5.1.3 on 2024-11-21 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_evento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='fin',
            new_name='fecha_fin',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='inicio',
            new_name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='titulo',
        ),
    ]
