# Generated by Django 5.1.3 on 2024-12-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_comuna_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='numero_telefono',
            field=models.CharField(max_length=9),
        ),
    ]
